---
openapi: "3.0.0"
servers: []
paths:
  /api/v1/users/{id}/quotations:
    get:
      summary: "getUserQuotationsHandler"
      description: "Get the list of Quotation object in the system, for a specific\
        \ User."
      tags:
      - "quotation-api"
      parameters:
      - name: "id"
        in: "path"
        description: "the user ID (currently the international phone number). This\
          \ parameter is mandatory."
        required: true
        schema: {}
      - name: "authorization"
        in: "header"
        description: "A JWT token to protect access to the API."
        required: true
        schema: {}
      responses:
        "200":
          description: "The array of Quotations for this User."
          headers:
            foo:
              description: "another output header"
              required: true
              schema: {}
            x-next:
              description: "The url to get the next page of results"
              required: true
              schema: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.Quotation_Array"
        "400":
          description: "An error message if the user id is invalid."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
      security: {}
    post:
      summary: "createUserQuotationHandler"
      description: "Create a new Quotation object in the system, for a specific User."
      tags:
      - "quotation-api"
      parameters:
      - name: "id"
        in: "path"
        description: "the user ID (currently the international phone\nnumber). This\
          \ parameter is mandatory."
        required: true
        schema: {}
      responses:
        "201":
          description: "The Payment,\nupdated with the creation timestamp."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.Quotation"
        "400":
          description: "An\nerror message if the Quotation attributes are invalid."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
      security: {}
      requestBody:
        description: "The Quotation object\nto create"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.agileandmore.examples.model.Quotation"
    servers: []
  /api/v1/gradles:
    post:
      summary: "createGradle"
      description: "Create a new Gradle in the system.\nBecause Gradles don't really\
        \ exist in real life, this does not create much."
      tags:
      - "gradle-api"
      parameters: []
      responses:
        "201":
          description: "if the Gradle has been created."
          headers: {}
        "409":
          description: "An error if the Gradle already exists."
          headers: {}
      security: {}
      requestBody:
        description: "A dummy message."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/java.lang.String"
    servers: []
  /api/v1/users:
    post:
      summary: "createUser"
      description: "Create a new User in the system."
      tags:
      - "user-api"
      parameters: []
      responses:
        "201":
          description: "The created User, with\nupdated information."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.model.User"
        "409":
          description: "An error if the User already exists."
          headers: {}
      security: {}
      requestBody:
        description: "The User to create."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.agileandmore.model.User"
    servers: []
  /api/v1/users/{mobile}:
    get:
      summary: "findUserByPhone"
      description: "Find a User by phone number."
      tags:
      - "user-api"
      parameters:
      - name: "mobile"
        in: "path"
        description: "the full international phone/mobile number of the user."
        required: true
        schema: {}
      responses:
        "200":
          description: "The User."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.User"
        "400":
          description: "An error message if the User is trying to query another User\n\
            information, but does not have the proper role to do so."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
        "404":
          description: "An error message if the User does not exist."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
      security: {}
    put:
      summary: "updateUserByPhone"
      description: "Update an existing User."
      tags:
      - "user-api"
      parameters: []
      responses:
        "200":
          description: "If the user has been updated with success."
          headers: {}
        "404":
          description: "An error message if the User does not exist."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
      security: {}
    delete:
      summary: "deleteUser"
      description: "Delete an existing User in the system."
      tags:
      - "user-api"
      parameters:
      - name: "mobile"
        in: "path"
        description: "the full international phone/mobile number of the user."
        required: true
        schema: {}
      responses:
        "204":
          description: "If the User has been deleted successfully."
          headers: {}
        "404":
          description: "An error message if the User does not exist."
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
      security: {}
    servers: []
components:
  schemas:
    com.agileandmore.examples.model.Quotation:
      type: "object"
      properties:
        amount:
          type: "number"
          description: "Amount for the quotation."
        referenceNumber:
          type: "string"
          description: "The quotation reference number."
        userId:
          type: "string"
          description: "The ID of the user this quotation is attached to."
      description: "A Quotation when a user wants to buy something."
    com.agileandmore.examples.model.User:
      type: "object"
      properties:
        firstName:
          type: "string"
          description: "User first name"
          minLength: 3
          maxLength: 50
        lastName:
          type: "string"
          description: "User last name"
        login:
          type: "string"
          description: "The login for the User. This is the email address."
          format: "email"
        password:
          type: "string"
          description: "User password."
      description: "A user in the system."
    com.agileandmore.examples.model.Quotation_Array:
      type: "array"
      items:
        $ref: "#/components/schemas/com.agileandmore.examples.model.Quotation"
    java.lang.String:
      type: "string"
    com.agileandmore.examples.model.views.ErrorMessage:
      type: "object"
      properties:
        message:
          type: "string"
          description: "The message of the error."
      description: "A normalized error message to return when something went wrong\
        \ in an API call."
