---
openapi: "3.0.0"
servers: []
paths:
  /api/v1/users/{id}/quotations:
    get:
      summary: "getUserQuotationsHandler"
      description: "Get the list of Quotation object in the system, for a specific\
        \ User."
      tags:
      - "quotation-api"
      parameters:
      - name: "id"
        in: "path"
        description: "the user ID (currently the international phone number). This\
          \ parameter is mandatory."
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "The array of Quotations for this User."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.Quotation_Array"
        "400":
          description: "An error message if the user id is invalid."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
    post:
      summary: "createUserQuotationHandler"
      description: "Create a new Quotation object in the system, for a specific User."
      tags:
      - "quotation-api"
      parameters:
      - name: "id"
        in: "path"
        description: "the user ID (currently the international phone\nnumber). This\
          \ parameter is mandatory."
        required: true
        schema:
          type: "string"
      responses:
        "201":
          description: "The Payment,\nupdated with the creation timestamp."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.Quotation"
        "400":
          description: "An\nerror message if the Quotation attributes are invalid."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
      requestBody:
        description: "The Quotation object\nto create"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.agileandmore.examples.model.Quotation"
  /api/v1/users:
    post:
      summary: "createUser"
      description: "Create a new User in the system."
      tags:
      - "user-api"
      parameters: []
      responses:
        "201":
          description: "The created User, with\nupdated information."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.model.User"
        "409":
          description: "An error if the User already exists."
      requestBody:
        description: "The User to create."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.agileandmore.model.User"
  /api/v1/users/{mobile}:
    get:
      summary: "findUserByPhone"
      description: "Find a User by phone number."
      tags:
      - "user-api"
      parameters:
      - name: "mobile"
        in: "path"
        description: "the full international phone/mobile number of the user."
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "The User."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.User"
        "400":
          description: "An error message if the User is trying to query another User\n\
            information, but does not have the proper role to do so."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
        "404":
          description: "An error message if the User does not exist."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
    put:
      summary: "updateUserByPhone"
      description: "Update an existing User."
      tags:
      - "user-api"
      parameters: []
      responses:
        "200":
          description: "If the user has been updated with success."
        "404":
          description: "An error message if the User does not exist."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
    delete:
      summary: "deleteUser"
      description: "Delete an existing User in the system."
      tags:
      - "user-api"
      parameters:
      - name: "mobile"
        in: "path"
        description: "the full international phone/mobile number of the user."
        required: true
        schema:
          type: "string"
      responses:
        "204":
          description: "If the User has been deleted successfully."
        "404":
          description: "An error message if the User does not exist."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.agileandmore.examples.model.views.ErrorMessage"
components:
  schemas:
    com.agileandmore.examples.model.Quotation:
      type: "object"
      properties:
        amount:
          type: "number"
          description: "Amount for the quotation."
        referenceNumber:
          type: "string"
          description: "The quotation reference number."
        userId:
          type: "string"
          description: "The ID of the user this quotation is attached to."
      description: "A Quotation when a user wants to buy something."
    com.agileandmore.examples.model.User:
      type: "object"
      properties:
        firstName:
          type: "string"
          description: "User first name"
        lastName:
          type: "string"
          description: "User last name"
        login:
          type: "string"
          description: "The login for the User. This is the email address."
        password:
          type: "string"
          description: "User password."
      description: "A user in the system."
    com.agileandmore.examples.model.Quotation_Array:
      type: "array"
      items:
        $ref: "#/components/schemas/com.agileandmore.examples.model.Quotation"
    com.agileandmore.examples.model.views.ErrorMessage:
      type: "object"
      properties:
        message:
          type: "string"
          description: "The message of the error."
      description: "A normalized error message to return when something went wrong\
        \ in an API call."
